amc/urls.py
from django.conf.urls import url

from amc import views

urlpatterns = [
    url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard'),

    url(r'^funds/$', views.SchemePlanList.as_view(), name='scheme_list'),
    url(r'^funds/(?P<scheme_id>[-_\w]+)/details$', views.scheme_detail, 
        name='scheme_detail'),
]

zcash/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from registration.backends.hmac.views import RegistrationView
from users import views
from django.utils.translation import ugettext_lazy as _


from users.forms import CustomUserCreationForm
from transactions import views as checkout_views

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls',
                                    'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^admin/', admin.site.urls),

    url(r'^amc/', include('amc.urls', namespace="amc")),
    url(r'^users/', include('users.urls', namespace="users")),

    url(r'^transactions/', include('transactions.urls')),
    url(r'^forum/', include('spirit.urls')),

    # url(r'^dashboard/', views.HomeView.as_view(), name='dashboard'),
    url(r'^$', views.IndexView.as_view(), name='index'),


    url(r'^accounts/register/$',
        RegistrationView.as_view(
            form_class=CustomUserCreationForm
        ),
        name='registration_register',
        ),
    url(r'^accounts/', include('registration.backends.hmac.urls')),

]

admin.site.site_header = _("Z-CASH Admin")
admin.site.site_title = _("Z-CASH Admin")

templates/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="{{ STATIC_URL }}style.css" />
    <title>{% block title %}Z-CASH{% endblock %}</title>
</head>

<body>
    <div id="header">
    {% block header %}

    {% if user.is_authenticated %}
        {% trans "Logged in" %}: {{ user.username }} 
        (<a href="{% url 'auth_logout' %}">{% trans "Log out" %}</a> | 
        <a href="{% url 'auth_password_change' %}">{% trans "Change password" %}</a>)
    {% else %}
       <a href="{% url 'auth_login' %}">{% trans "Log in" %}</a>
    {% endif %}

    {% endblock %}
    </div>

    <div id="content">
    {% block content %}{% endblock %}
    </div>

    <div id="footer">
    {% block footer %}
    {% endblock %}
    </div>
</body>

</html>

templates/portfolio.html
 {% extends "template.html" %} {% block portfolio %}

<div class="col-md-12">
    <div class="card card-plain">
        <div class="header">
            <h4 class="title">Portfolio Details</h4>

        </div>
        <div class="content table-responsive table-full-width">
            <table class="table table-hover">
                <thead>
                    <th>Scheme Plan</th>
                    <th>Transaction Type</th>
                    <th>Amount</th>
                    <th>Transaction Status</th>
                </thead>
                <tbody>
                    {% for transaction in transactions %}

                    <tr>
                        <td>{{ transaction.scheme_plan.name}}</td>
                        <td>{{ transaction.transaction_type}}</td>
                        <td>{{ transaction.amount }}</td>
                        <td>{{ transaction.status }}</td>
                    </tr>
                    {% endfor %}


                </tbody>
            </table>

        </div>
    </div>
</div>

{% endblock %}

templates/scheme_list.html
{% extends "template.html" %} {% block content %} {% for scheme in object_list %}
<div class="col-md-4">
    <div class="card ">
        <div class="header">
            <h4 class="title">{{ scheme.name }}</h4>
            <hr>
            <p><b>Parent Fund:</b>  {{ scheme.fund_scheme }}</p>
            <p><b>Minimum Investment:</b> {{ scheme.min_investment }} </p>
            <a class="btn btn-block" href="{% url 'amc:scheme_detail' scheme.id %}" role="button">Details</a>
        </div>
        <hr>
    </div>
</div>
{% endfor %} {% endblock %}

templates/user_update_form.html
{% extends "template.html" %} {% load widget_tweaks %} {% block content %}

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Edit Profile</h4>
                    </div>
                    <div class="content">
                        <form method="post">{% csrf_token %}
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Username</label>
                                        {{ form.username|add_class:"form-control"}}
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Email address</label>
                                        {{ form.email|add_class:"form-control" }}
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>First Name</label>
                                        {{ form.first_name|add_class:"form-control" }}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Last Name</label>
                                        {{ form.last_name|add_class:"form-control" }} </div>
                                </div>

                            </div>


                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>National ID No.</label>
                                        {{ form.national_id|add_class:"form-control" }}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Mobile Phone</label>
                                        {{ form.phone|add_class:"form-control" }}
                                    </div>
                                </div>
                            </div>
                            <div class="row">

                            </div>

                            <button type="submit" class="btn btn-info btn-fill pull-right">Update Profile</button>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</script> {% endblock %}