amc/urls.py
from django.conf.urls import url

from amc import views

urlpatterns = [
    url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard'),

    url(r'^funds/$', views.SchemePlanList.as_view(), name='scheme_list'),
    url(r'^funds/(?P<scheme_id>[-_\w]+)/details$', views.scheme_detail, 
        name='scheme_detail'),
]

users/urls.py
from django.conf.urls import url

from users import views

urlpatterns = [
    url(r'^profile/update/(?P<pk>[-\w]+)/$',
        views.UserUpdate.as_view(), name='profile'),
    url(r'^profile/portfolio/',
        views.portfolio, name='portfolio'),

]

zcash/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from registration.backends.hmac.views import RegistrationView
from users import views
from django.utils.translation import ugettext_lazy as _


from users.forms import CustomUserCreationForm
from transactions import views as checkout_views

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls',
                                    'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^admin/', admin.site.urls),

    url(r'^amc/', include('amc.urls', namespace="amc")),
    url(r'^users/', include('users.urls', namespace="users")),

    url(r'^transactions/', include('transactions.urls')),
    url(r'^forum/', include('spirit.urls')),

    # url(r'^dashboard/', views.HomeView.as_view(), name='dashboard'),
    url(r'^$', views.IndexView.as_view(), name='index'),


    url(r'^accounts/register/$',
        RegistrationView.as_view(
            form_class=CustomUserCreationForm
        ),
        name='registration_register',
        ),
    url(r'^accounts/', include('registration.backends.hmac.urls')),

]

admin.site.site_header = _("Z-CASH Admin")
admin.site.site_title = _("Z-CASH Admin")

templates/dashboard/dashboard.html
{% extends "template.html" %} {% load static %} {% block content %}
<div class="content">
    <div class="container-fluid">
        <div class="row">


        </div>



        <!-- <div class="row">
            <div class="col-md-6">
                <div class="card ">
                    <div class="header">
                        <h4 class="title">Old Mutual vs Sanlam</h4>
                        <p class="category">Dividend Yields on Money Market Funds</p>
                    </div>
                    <div class="content">
                        <div id="chartActivity" class="ct-chart"></div>

                        <div class="footer">
                            <div class="legend">
                                <i class="fa fa-circle text-info"></i> Sanlam
                                <i class="fa fa-circle text-danger"></i> Old Mutual
                            </div>
                            <hr>
                            <div class="stats">
                                <i class="fa fa-check"></i> Data information certified
                            </div>
                        </div>
                    </div>
                </div>
            </div> -->
        {% block chart %}

        <div class="row">
            <div class="col-lg-12">
                <!-- TradingView Widget BEGIN -->
                <!-- TradingView Widget BEGIN -->
                <script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
                <script type="text/javascript">
                    new TradingView.widget({
                        "width": 980,
                        "height": 610,
                        "symbol": "NASDAQ:AAPL",
                        "interval": "D",
                        "timezone": "Etc/UTC",
                        "theme": "Light",
                        "style": "0",
                        "locale": "en",
                        "toolbar_bg": "#f1f3f6",
                        "enable_publishing": false,
                        "withdateranges": true,
                        "hide_side_toolbar": false,
                        "allow_symbol_change": true,
                        "details": true,
                        "calendar": true,
                        "news": [
                            "headlines"
                        ],
                        "hideideas": true
                    });
                </script>
                <!-- TradingView Widget END -->

            </div>

        </div>
        {% endblock chart %}

    </div>
</div>
{% endblock %}

templates/dashboard/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}
    Document
    {% endblock title %}</title>
</head>Document

<body>
    {% block pagecontent %}
        <p>pagecontent</p> 
    {% endblock pagecontent %}
</body>

</html>

templates/dashboard/registration_form.html
{% extends "signup.html" %} 

{% load widget_tweaks %} 
{% block content %}
<form method="post">{% csrf_token %}
    <div class="col-md-6 right-side">
        <span class="input input--hoshi">
            {{ form.username|add_class:"input__field input__field--hoshi" }}
            <label class="input__label input__label--hoshi input__label--hoshi-color-3" for="username">
                <span class="input__label-content input__label-content--hoshi">Username</span>
            </label>
        </span>
        <span class="input input--hoshi">
            {{ form.email|add_class:"input__field input__field--hoshi" }}
            <label class="input__label input__label--hoshi input__label--hoshi-color-3" for="email">
                <span class="input__label-content input__label-content--hoshi">Email</span>
            </label>
        </span>
        <span class="input input--hoshi">
            {{ form.password1|add_class:"input__field input__field--hoshi"}}
            <label class="input__label input__label--hoshi input__label--hoshi-color-3" for="username">
                <span class="input__label-content input__label-content--hoshi">Password</span>
            </label>
        </span>
        <span class="input input--hoshi">
            {{ form.password2|add_class:"input__field input__field--hoshi" }}
            <label class="input__label input__label--hoshi input__label--hoshi-color-3" for="username">
                <span class="input__label-content input__label-content--hoshi">Repeat Password</span>
            </label>
        </span>
        <div class="cta">
            <button class="btn btn-primary pull-left" type="submit">
                Sign-Up Now
            </button>
            <span>
                <a href="#">I am already a member</a>
            </span>
        </div>
</form>
{% endblock %}

templates/dashboard/scheme_detail.html
{% extends "template.html" %} {% block content %} {% load widget_tweaks %}
<div class="content">
    <div class="container-fluid">
        {% block chart %}
        <div class="row">
            <div class="col-md-6">
                <!-- TradingView Widget BEGIN -->
                <script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
                <script type="text/javascript">
                    new TradingView.widget({
                        "width": 500,
                        "height": 500,
                        "symbol": "FX:EURUSD",
                        "interval": "5",
                        "timezone": "Europe/Istanbul",
                        "theme": "Light",
                        "style": "1",
                        "locale": "en",
                        "toolbar_bg": "#f1f3f6",
                        "enable_publishing": false,
                        "allow_symbol_change": true,
                        "details": true,
                        "calendar": true,
                        "news": [
                            "headlines"
                        ],
                        "hideideas": true,
                        "show_popup_button": true,
                        "popup_width": "1000",
                        "popup_height": "650"
                    });
                </script>
                <!-- TradingView Widget END -->

            </div>
            <div class="col-md-6">
                <div class="card ">
                    <div class="header">
                        <h4 class="title">{{ scheme.name }}</h4>
                        <p class="category">Asset size: Ksh{{ scheme.asset_size }}</p>
                        <p class="category">Launch Date: {{ scheme.launch_date }}</p>
                        <a href="/forum/topic/1/what-is-an-expense-ratio/">
                            <p class="category" style="cursor:help">Expense Ratio:{{ scheme.expense_ratio }}</p>
                        </a>
                    </div>
                    <div class="content">

                        <div class="footer">

                            <hr>
                            <div class="stats">
                                <a href="{% url 'checkout' scheme.pk %}">
                                    <button class="btn"> Invest</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>


</div>
{% endblock chart %} {% endblock %}

templates/dashboard/signup.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <title></title>

  <!-- Stylesheets -->
  <link rel="stylesheet" href="{% static "assets/css/style.css"%}">
  <link rel="stylesheet" href="{% static "assets/css/set1.css"%}">

  <!--Google Fonts-->
  <link href='https://fonts.googleapis.com/css?family=Playfair+Display' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>

</head>

<body>
<div id="main-wrapper">

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6 left-side">
        <header>
          <span>Need an account?</span>
          <h3>Create Account<br>Make Profits</h3>
          <a href="{% url 'index' %}"><span> Go Back </span></a>
        </header>
      </div>
      {% block content %}
      {% endblock %}
        
      </div>
    </div>
  </div>

</div> <!-- end #main-wrapper -->

<!-- Scripts -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="{% static "assets/js/scripts.js"%}"></script>
<script src="{% static "assets/js/classie.js"%}"></script>
<script>
  (function() {
    // trim polyfill : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim
    if (!String.prototype.trim) {
      (function() {
        // Make sure we trim BOM and NBSP
        var rtrim = /^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g;
        String.prototype.trim = function() {
          return this.replace(rtrim, '');
        };
      })();
    }

    [].slice.call( document.querySelectorAll( 'input.input__field' ) ).forEach( function( inputEl ) {
      // in case the input is already filled..
      if( inputEl.value.trim() !== '' ) {
        classie.add( inputEl.parentNode, 'input--filled' );
      }

      // events:
      inputEl.addEventListener( 'focus', onInputFocus );
      inputEl.addEventListener( 'blur', onInputBlur );
    } );

    function onInputFocus( ev ) {
      classie.add( ev.target.parentNode, 'input--filled' );
    }

    function onInputBlur( ev ) {
      if( ev.target.value.trim() === '' ) {
        classie.remove( ev.target.parentNode, 'input--filled' );
      }
    }
  })();
</script>

</body>
</html>
            

templates/dashboard/template.html
{% load static %}
{% load i18n %}
{% load widget_tweaks %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <link rel="icon" type="image/png" href="assets/img/favicon.ico">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    
        <title>Z-CASH</title>
    
        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
        <meta name="viewport" content="width=device-width" />
    
    
        <!-- Bootstrap core CSS     -->
        <link href="{% static "assets/css/bootstrap.min.css"%}" rel="stylesheet" />
    
        <!-- Animation library for notifications   -->
        <link href="{% static "assets/css/animate.min.css"%}" rel="stylesheet" />
    
        <!--  Light Bootstrap Table core CSS    -->
        <link href="{% static "assets/css/light-bootstrap-dashboard.css" %}" rel="stylesheet" />
    
        <!--     Fonts and icons     -->
        <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
        <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
        <link href="{% static "assets/css/pe-icon-7-stroke.css"%}" rel="stylesheet" />
    
    </head>
<body>

<div class="wrapper">
    <div class="sidebar" data-color="purple" data-image="{% static "assets/img/sidebar-5.jpg"%}">

    <!--

        Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
        Tip 2: you can also add an image using data-image tag

    -->

    	<div class="sidebar-wrapper">
            <div class="logo">
                <a href="{% url 'index' %}" class="simple-text">
                    Z-CASH
                </a>
            </div>
            {% url 'amc:dashboard' as home %}
            {% url 'amc:scheme_list' as schemes %}
            {% url 'users:profile' user.pk as profile %}
            {% url 'users:portfolio' user.id as portfolio %}
            

            

            <ul class="nav">
                <li {% if request.path == home %} class="active" {% endif %}>
                    <a href="{% url 'amc:dashboard' %}">
                        <i class="pe-7s-graph"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li {% if request.path == schemes %} class="active"{% endif %}>
                        <a href="{% url 'amc:scheme_list' %}">
                            <i class="pe-7s-piggy"></i>
                            <p>Funds</p>
                        </a>
                    </li>
                <li {% if request.path == portfolio %}class="active"{% endif %}>
                        <a href="{% url 'users:portfolio'  %}">
                        <i class="pe-7s-graph"></i>
                        <p>Your Portfolio</p>
                    </a>
                </li>
                <li {% if request.path == profile %} class="active"{% endif %}>
                    <a href="{% url 'users:profile' user.pk %}">
                        <i class="pe-7s-users"></i>
                        <p>Profile</p>
                    </a>
                </li>
                

            </ul>
    	</div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Points:{{ request.user.points }}</a>
                    
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-left">
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-dashboard"></i>
                            </a>
                        </li>
                        
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            {% if user.is_authenticated %}<a href ="">{{ request.user.username }} </a>
                        </li>
                        <li>
                            <a href="{% url 'auth_logout' %}">{% trans "Log out" %}</a>     
                        </li>
                            {% else %}
                        <li>                               
                            <a href="{% url 'auth_login' %}">{% trans "Log in" %}</a>
                        </li>
                            {% endif %}
                    </ul>
                </div>
            </div>
        </nav>


        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    {% block content %}
                    
                    {% endblock %} 
                    {% block portfolio %}
                    
                    {% endblock portfolio %}
                    
                </div>
            </div>
        </div>


        <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul>
                        <li>
                            <a href="{% url 'index' %}">
                                Landing Page
                            </a>
                        </li>
                        

                    </ul>
                </nav>
            </div>
        </footer>

    </div>
</div>


</body>

    <!--   Core JS Files   -->
    <script src="{% static "assets/js/jquery.3.2.1.min.js"%}" type="text/javascript"></script>
	<script src="{% static "assets/js/bootstrap.min.js"%}" type="text/javascript"></script>

	<!--  Charts Plugin -->
	<script src="{% static "assets/js/chartist.min.js"%}"></script>

    <!--  Notifications Plugin    -->
    <script src="{% static "assets/js/bootstrap-notify.js"%}"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
	<script src="{% static "assets/js/light-bootstrap-dashboard.js"%}"></script>

	<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
	<script src="{% static "assets/js/demo.js"%}"></script>
    
    {% block script %}
    {% if request.user.is_authenticated %}
    <script type="text/javascript">
    	$(document).ready(function(){

        	demo.initChartist();


    	});
	</script>
        
    {% endif %}
    
    
    {% endblock %}      
	


</html>